version: "3.4"

services:
  governace_ceremony:
    image: ${CEREMONY_IMAGE}:${CEREMONY_VERSION}
    ports:
      - "3000:3000"
    volumes:
      - ../../secret/ws_secret.json:/eth-netstats
    restart: always